FROM golang:1.23-alpine3.22 AS builder

RUN apk add --no-cache git ca-certificates bash
WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /gitlab-labelctl ./cmd/gitlab-labelctl

FROM alpine:3.22
RUN apk add --no-cache ca-certificates bash
COPY --from=builder /gitlab-labelctl /usr/local/bin/gitlab-labelctl
ENTRYPOINT ["/usr/local/bin/gitlab-labelctl"]
